name: docker-build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
env:
  APP_NAME: base-ts-node
  REVISION: ${{ github.event.pull_request.head.sha }}
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: docker build
        run: |
          docker build . \
            --tag ${{ env.APP_NAME }}:${{ env.REVISION }} \
            --build-arg APP_NAME \
            --build-arg REVISION
      - name: docker run
        run: |
          docker run \
            --rm \
            --env CI=true \
            --env FOO=foo \
            --env BAR=bar \
            ${{ env.APP_NAME }}:${{ env.REVISION }}
